Tabule audio: Giving up on VLC

diff --git a/libexec/opentabule/tabule-audio-sender b/libexec/opentabule/tabule-audio-sender
--- a/libexec/opentabule/tabule-audio-sender
+++ b/libexec/opentabule/tabule-audio-sender
@@ -5,11 +5,12 @@ if [ "x${HOST}" = "x" ] ; then
 fi
 
 # resolve ipv4 addr, as gstreamer preffers system default - due to vlc bug
-HOST="$(getent ahostsv4 tabule.lan | grep DGRAM | cut -d' ' -f1 2>/dev/null)"
-if [ "x$HOST" = x ] ; then
-	echo "could not resolve DGRAM ipv4 host" 1>&2
-	exit 1
-fi
+#HOST="$(getent ahostsv4 tabule.lan | grep DGRAM | cut -d' ' -f1 2>/dev/null)"
+#if [ "x$HOST" = x ] ; then
+#	echo "could not resolve DGRAM ipv4 host" 1>&2
+#	exit 1
+#fi
 
 echo 'Launching broadcast'
-gst-launch-1.0 -v pulsesrc device = combined.monitor ! audio/x-raw,channels=2 ! queue ! faac ! mpegtsmux ! rtpmp2tpay ! udpsink host = "${HOST}" port = 5004
+gst-launch-1.0 -v pulsesrc device = combined.monitor ! audio/x-raw,channels=2 ! queue min-threshold-time = 1000000000 ! opusenc ! rtpopuspay ! udpsink host = "${HOST}" port = 5004
+
